version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres-sending-application
    restart: always
    environment:
      POSTGRES_DB: sendingApplication
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data